// Qa Lab plugin module provides the WhatsApp fake-provider preload source.
export const WHATSAPP_FAKE_PROVIDER_PRELOAD_SOURCE = `// Generated by QA Lab to register a WhatsApp fake-provider controller.
import {
  registerWhatsAppConnectionController,
  unregisterWhatsAppConnectionController,
} from "@openclaw/whatsapp/api.js";

const REGISTRATION_STATE_KEY = Symbol.for("openclaw.qaLab.whatsappFakeProviderRegistration");

function readNonEmptyString(value) {
  const trimmed = typeof value === "string" ? value.trim() : "";
  return trimmed || null;
}

function e164FromJid(jid) {
  const waId = String(jid).split("@", 1)[0]?.split(":", 1)[0] ?? "";
  return /^\\d+$/u.test(waId) ? \`+\${waId}\` : null;
}

function readRegistrationState() {
  return globalThis[REGISTRATION_STATE_KEY] ?? null;
}

function writeRegistrationState(state) {
  if (state) {
    globalThis[REGISTRATION_STATE_KEY] = state;
  } else {
    delete globalThis[REGISTRATION_STATE_KEY];
  }
}

function createActiveListener(socket) {
  return {
    async close() {},
    async sendComposingTo(to) {
      await socket.sendPresenceUpdate("composing", to);
    },
    async sendMessage(to, text, mediaBuffer, mediaType) {
      if (mediaBuffer || mediaType) {
        throw new Error("WhatsApp fake-provider controller supports text sends only.");
      }
      const message = await socket.sendMessage(to, { text });
      const key = message.key ?? {};
      const messageId = typeof key.id === "string" && key.id.trim() ? key.id : "unknown";
      return {
        kind: "text",
        keys: [{
          ...(key.participant ? { participant: key.participant } : {}),
          fromMe: key.fromMe === true,
          id: messageId,
          remoteJid: key.remoteJid,
        }],
        messageId,
        providerAccepted: true,
      };
    },
    async sendPoll() {
      throw new Error("WhatsApp fake-provider controller does not support poll sends.");
    },
    async sendReaction() {
      throw new Error("WhatsApp fake-provider controller does not support reaction sends.");
    },
  };
}

async function registerFromEnv() {
  const accessToken = readNonEmptyString(process.env.OPENCLAW_WHATSAPP_FAKE_PROVIDER_ACCESS_TOKEN);
  const apiRoot = readNonEmptyString(process.env.OPENCLAW_WHATSAPP_FAKE_PROVIDER_API_ROOT);
  if (!accessToken || !apiRoot) {
    return;
  }
  const accountId = readNonEmptyString(process.env.OPENCLAW_WHATSAPP_FAKE_PROVIDER_ACCOUNT_ID) ?? "default";
  const selfJid = readNonEmptyString(process.env.OPENCLAW_WHATSAPP_FAKE_PROVIDER_SELF_JID) ?? "15550000000@s.whatsapp.net";
  const existing = readRegistrationState();
  if (existing?.accountId === accountId) {
    return;
  }
  if (existing) {
    unregisterWhatsAppConnectionController(existing.accountId, existing.controller);
  }
  const crabline = await import("@openclaw/crabline");
  if (typeof crabline.createWhatsAppBaileysMockSocket !== "function") {
    throw new Error("@openclaw/crabline does not expose createWhatsAppBaileysMockSocket(). Install a version with WhatsApp fake-provider support.");
  }
  const socket = crabline.createWhatsAppBaileysMockSocket({ accessToken, apiRoot, selfJid });
  const listener = createActiveListener(socket);
  const controller = {
    getActiveListener: () => listener,
    getCurrentSock: () => socket,
    getSelfIdentity: () => ({
      e164: e164FromJid(selfJid),
      jid: selfJid,
      lid: null,
    }),
  };
  registerWhatsAppConnectionController(accountId, controller);
  writeRegistrationState({ accountId, controller });
}

await registerFromEnv();
`;
